---
- hosts: dev
  tasks:
    - name: pull docker images from registory
      raw: docker pull veenadevops/mydevops:3.0
            
    - name: bringup container
      raw: docker run -dti --name webapp -p 80:80 veenadevops/mydevops:3.0 /bin/bash

